### ISSUE TITLE
Error for compile in win10

### ISSUE THREAD

**Issue by huk87** [albertobsd/keysubtracter#17]
`PS E:\b\ROTOR\tests\keysubtracter-main> g++ -c keysubtracter.c
PS E:\b\ROTOR\tests\keysubtracter-main> g++ keysubtracter.c
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x3a): undefined reference to `__gmpz_init_set_str'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x57): undefined reference to `__gmpz_init_set_str'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x74): undefined reference to `__gmpz_init_set_str'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x91): undefined reference to `__gmpz_init_set_str'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x9d): undefined reference to `init_doublingG(Point*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xa9): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xb5): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xc1): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xd5): undefined reference to `__gmpz_init_set_ui'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xe1): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xf5): undefined reference to `__gmpz_init_set_ui'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x37d): undefined reference to `__gmpz_sub'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x389): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x395): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x3a1): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x3ad): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x3b9): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x3c5): more undefined references to `__gmpz_init' follow
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x40e): undefined reference to `__gmp_randinit_mt'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x433): undefined reference to `__gmp_randseed_ui'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x47a): undefined reference to `__gmpz_urandomm'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x4c4): undefined reference to `Scalar_Multiplication(Point, Point*, __mpz_struct*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x4d8): undefined reference to `Point_Negation(Point*, Point*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x4f4): undefined reference to `Point_Addition(Point*, Point*, Point*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x508): undefined reference to `__gmpz_tstbit'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x530): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x556): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x572): undefined reference to `Point_Addition(Point*, Point*, Point*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x586): undefined reference to `__gmpz_tstbit'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x5ae): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x5d4): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x5f7): undefined reference to `__gmpz_tstbit'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x617): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x638): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x660): undefined reference to `__gmpz_cdiv_q_ui'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x6aa): undefined reference to `Scalar_Multiplication(Point, Point*, __mpz_struct*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x6be): undefined reference to `__gmpz_set'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x6d2): undefined reference to `__gmpz_set'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x6e6): undefined reference to `__gmpz_set'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x725): undefined reference to `Point_Negation(Point*, Point*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x741): undefined reference to `Point_Addition(Point*, Point*, Point*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x755): undefined reference to `__gmpz_tstbit'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x77d): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x7a3): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x7bf): undefined reference to `Point_Addition(Point*, Point*, Point*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x7d3): undefined reference to `__gmpz_tstbit'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x7fb): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x821): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x83d): undefined reference to `Point_Addition(Point*, Point*, Point*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x851): undefined reference to `__gmpz_set'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x865): undefined reference to `__gmpz_set'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x881): undefined reference to `__gmpz_add'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x8a4): undefined reference to `__gmpz_tstbit'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x8c4): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x8e2): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x8ee): undefined reference to `__gmpz_clear'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x8fa): undefined reference to `__gmpz_clear'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x906): undefined reference to `__gmpz_clear'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x912): undefined reference to `__gmpz_clear'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x91e): undefined reference to `__gmpz_clear'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0x92a): more undefined references to `__gmpz_clear' follow
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xa5a): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xa77): undefined reference to `__gmpz_pow_ui'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xa8a): undefined reference to `__gmpz_set'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xaa4): undefined reference to `__gmpz_pow_ui'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xabe): undefined reference to `__gmpz_sub_ui'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xad1): undefined reference to `__gmpz_set'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xaf1): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xb11): undefined reference to `__gmp_fprintf'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xb1c): undefined reference to `__gmpz_clear'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xbfc): undefined reference to `trim(char*, char const*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xc3c): undefined reference to `__gmpz_set_str'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xc76): undefined reference to `__gmpz_set_str'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xcae): undefined reference to `__gmpz_set_str'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xcdf): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xcea): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xcf5): undefined reference to `__gmpz_init'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xd10): undefined reference to `__gmpz_pow_ui'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xd2a): undefined reference to `__gmpz_add_ui'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xd44): undefined reference to `__gmpz_mod'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xd5f): undefined reference to `__gmpz_add_ui'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xd79): undefined reference to `__gmpz_fdiv_q_ui'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xd9b): undefined reference to `__gmpz_powm'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xdb6): undefined reference to `__gmpz_sub'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xde2): undefined reference to `__gmpz_tstbit'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xdfa): undefined reference to `__gmpz_set'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xe10): undefined reference to `__gmpz_tstbit'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xe27): undefined reference to `__gmpz_set'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xe63): undefined reference to `__gmpz_clear'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xe6e): undefined reference to `__gmpz_clear'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xe79): undefined reference to `__gmpz_clear'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xf2b): undefined reference to `stringtokenizer(char*, str_tokenizer*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xf3e): undefined reference to `nextToken(str_tokenizer*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xf56): undefined reference to `__gmpz_init_set_str'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xf61): undefined reference to `nextToken(str_tokenizer*)'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xf79): undefined reference to `__gmpz_init_set_str'
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\kevla\AppData\Local\Temp\ccKHk5uA.o:keysubtracter.c:(.text+0xf84): undefined reference to `freetokenizer(str_tokenizer*)'
collect2.exe: error: ld returned 1 exit status`

**Comment by albertobsd** [comment]
Please install or search the way to use libgmp, i never try to compile the program directly in Windows.

I recommend to you use the ubuntu shell available in windows 10 Store

**Comment by WanderingPhilosopher** [comment]
Here is the Windows version:

https://github.com/WanderingPhilosopher/Windows-KeySubtractor

 If Windows users wish to compile on their own, I followed this guide  https://www.msys2.org/  to download, install, setup the mingw-w64 GCC. Follow the instructions. Once complete, you can go to the above github page that has my Windows release and download the files and unzip. Open up MSYS MinGW 64-bit, do a cd (change directory) to the folder containing the files. Once there, simply type in make.

Enjoy.

**Comment by albertobsd** [comment]
Thanks @WanderingPhilosopher
